### ISSUE TITLE
Improve way of user creation

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-elasticsearch#1]
There are better ways in the official role ( https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/xpack/security/elasticsearch-security.yml ) . Maybe they are not perfect but we can learn from them.

At least place the generated passwords in a secure directory for starters

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
