### ISSUE TITLE
Introduce certificate renewal

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-elasticsearch#41]
We create certificates with this role but we can't renew them automatically. We need a way to renew certificates.

Maybe that means that we have to delete certificates before rerunning the role but I'm positive, we can come up with something more sophisticated.

When we found a way we need the same procedure in our other roles for the Elastic Stack.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
