### ISSUE TITLE
Make sure that check mode works

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-elasticsearch#46]
Right now we are checking for bootstrap passwords, copy certificates and more. When running in `--check` mode these tasks are skipped and the following fail (e.g. copy the certificates to the actual node).

There are several ways to skip some tasks when running in `--check` mode, we should use one of them.

**Comment by widhalmt** [comment]
@zerwes - you proposed a solution for that. You said, you'd be kind enough to provide us with a PR which would be very much appreciated.

**Comment by zerwes** [comment]
PR #49 opened

**Comment by widhalmt** [comment]
Thanks a lot! That really helps fixing a problem that bugged us in several setups.
