### ISSUE TITLE
Set defaults for all variables and mention them

### ISSUE THREAD

**Issue by Crited** [NETWAYS/ansible-role-elasticsearch#5]
All variables should be mentioned, inside the `defaults/main.yml` even if not used and if possible or necessary have default values.

Like #3 `elastic_stack_full_stack` is necessary for the purpose of running the playbook at bare minimum configuration.

Others like `logstash_user` should be like: `logstash_system`
`logstash_password` could be left empty, but atleast be there as a comment.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
