### ISSUE TITLE
Add inventory_hostname to certificate alt names

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-elasticsearch#55]
Especially when running in test environments but also in multi-homed environments we need a way to add more names to the certificates.

Adding the `inventory_hostname` could be a first step. Making it optionally configurable would be better (and could be another issue)

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
