### ISSUE TITLE
Overhaul tags in the playbook

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-elasticsearch#78]
This is connected with NETWAYS/ansible-collection-elasticstack#67 . It seems that the first attempt to introduce tags wasn't very succesful. There are errors and they are not intuitively usable.

This issue is an attempt to start anew und make it right.

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
